before_script: cd Example
language: objective-c
osx_image: xcode8.2
sudo: false
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=Example.xcworkspace
    - IOS_SCHEME="Example"
    - IOS_SDK=iphonesimulator10.2
  matrix:
    - DESTINATION="OS=9.3,name=iPhone 5s"
    - DESTINATION="OS=10.2,name=iPhone 7"

script:
  - set -o pipefail
  # Build the Example project
  - pod repo update
  - pod install
  - xctool -workspace "$WORKSPACE" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION"
  - cd ..
  - pod lib lint
