language: objective-c
osx_image: xcode8.2.1
sudo: false
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=Example/Example.xcworkspace
    - IOS_SCHEME="Example"
    - IOS_SDK=iphonesimulator
  matrix:
    - DESTINATION="OS=8.4,name=iPhone 6"
    - DESTINATION="OS=9.3,name=iPhone 5s"
    - DESTINATION="OS=10.2,name=iPhone 7"

script:
  - set -o pipefail
  - pod install
  # Build Framework and Run Tests
  - xctool -workspace "$WORKSPACE" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION"
  - pod lib lint
  